### ISSUE TITLE
Unable to open project in Intellij IDEA

### ISSUE THREAD

**Issue by dluc** [playframework/play-java-rest-api-example#32] opened 2017-11-06 20:34 UTC
After cloning the repo, I cannot open it with IntelliJ IDEA. When I run Project->Open I get a "Resolve Error"

![image](https://user-images.githubusercontent.com/371009/32462528-9068c5ec-c2ee-11e7-9d10-abee3891de58.png)

Full log:
```
[info] Loading global plugins from ~/.sbt/0.13/plugins
[info] Loading project definition from /..../play-java-rest-api-example/project
[info] Updating {file:/..../play-java-rest-api-example/project/}play-java-rest-api-example-build...
[info] Resolving org.scala-sbt#global-plugins;0.0 ...
[info] Resolving com.typesafe.play#sbt-plugin;2.6.7 ...
[info] Resolving com.typesafe.play#sbt-routes-compiler_2.10;2.6.7 ...
[info] Resolving org.scala-lang#scala-library;2.10.6 ...
[info] Resolving com.typesafe.play#twirl-api_2.10;1.3.12 ...
[info] Resolving commons-io#commons-io;2.5 ...
[info] Resolving com.typesafe.play#run-support_2.10;2.6.7 ...
[info] Resolving com.typesafe.play#build-link;2.6.7 ...
[info] Resolving com.typesafe.play#play-exceptions;2.6.7 ...
[info] Resolving com.lightbend.play#play-file-watch_2.10;1.0.0 ...
[info] Resolving com.lightbend.play#jnotify;0.94-play-2 ...
[info] Resolving com.github.pathikrit#better-files_2.10;2.14.0 ...
[info] Resolving com.typesafe#config;1.3.1 ...
[info] Resolving org.slf4j#slf4j-simple;1.7.25 ...
[info] Resolving org.slf4j#slf4j-api;1.7.25 ...
[info] Resolving com.typesafe.sbt#sbt-twirl;1.3.12 ...
[info] Resolving com.typesafe.play#twirl-compiler_2.10;1.3.12 ...
[info] Resolving org.scala-lang#scala-compiler;2.10.6 ...
[info] Resolving org.scala-lang#scala-reflect;2.10.6 ...
[info] Resolving com.typesafe.play#twirl-parser_2.10;1.3.12 ...
[info] Resolving com.typesafe.sbt#sbt-native-packager;1.3.1 ...
[info] Resolving org.apache.commons#commons-compress;1.14 ...
[info] Resolving org.apache.ant#ant;1.10.1 ...
[info] Resolving org.apache.ant#ant-launcher;1.10.1 ...
[info] Resolving com.lightbend.sbt#sbt-javaagent;0.1.4 ...
[info] Resolving com.typesafe.sbt#sbt-web;1.4.3 ...
[info] Resolving com.typesafe.akka#akka-actor_2.10;2.3.16 ...
[info] Resolving org.webjars#webjars-locator-core;0.33 ...
[info] Resolving org.apache.commons#commons-lang3;3.1 ...
[info] Resolving com.fasterxml.jackson.core#jackson-core;2.7.3 ...
[info] Resolving com.typesafe.sbt#sbt-js-engine;1.2.2 ...
[info] Resolving com.typesafe#jse_2.10;1.2.3 ...
[info] Resolving com.typesafe.akka#akka-contrib_2.10;2.3.16 ...
[info] Resolving com.typesafe.akka#akka-remote_2.10;2.3.16 ...
[info] Resolving io.netty#netty;3.8.0.Final ...
[info] Resolving com.google.protobuf#protobuf-java;2.5.0 ...
[info] Resolving org.uncommons.maths#uncommons-maths;1.2.2a ...
[info] Resolving com.typesafe.akka#akka-cluster_2.10;2.3.16 ...
[info] Resolving com.typesafe.akka#akka-persistence-experimental_2.10;2.3.16 ...
[info] Resolving org.iq80.leveldb#leveldb;0.5 ...
[info] Resolving org.iq80.leveldb#leveldb-api;0.5 ...
[info] Resolving com.google.guava#guava;12.0 ...
[info] Resolving com.google.code.findbugs#jsr305;1.3.9 ...
[info] Resolving org.fusesource.leveldbjni#leveldbjni-all;1.7 ...
[info] Resolving org.fusesource.leveldbjni#leveldbjni;1.7 ...
[info] Resolving org.fusesource.hawtjni#hawtjni-runtime;1.8 ...
[info] Resolving org.fusesource.leveldbjni#leveldbjni-osx;1.5 ...
[info] Resolving org.fusesource.leveldbjni#leveldbjni-linux32;1.5 ...
[info] Resolving org.fusesource.leveldbjni#leveldbjni-linux64;1.5 ...
[info] Resolving org.fusesource.leveldbjni#leveldbjni-win32;1.5 ...
[info] Resolving org.fusesource.leveldbjni#leveldbjni-win64;1.5 ...
[info] Resolving io.apigee.trireme#trireme-core;0.8.9 ...
[info] Resolving io.apigee.trireme#trireme-kernel;0.8.9 ...
[info] Resolving org.mozilla#rhino;1.7.7.1 ...
[info] Resolving io.apigee.trireme#trireme-node10src;0.8.9 ...
[info] Resolving io.spray#spray-json_2.10;1.3.3 ...
[info] Resolving com.typesafe#npm_2.10;1.2.1 ...
[info] Resolving org.webjars#npm;4.2.0 ...
[info] Resolving io.gatling#gatling-sbt;2.2.2 ...
[info] Resolving org.scala-sbt#sbt;0.13.15 ...
[info] Resolving org.scala-sbt#main;0.13.15 ...
[info] Resolving org.scala-sbt#actions;0.13.15 ...
[info] Resolving org.scala-sbt#classpath;0.13.15 ...
[info] Resolving org.scala-sbt#interface;0.13.15 ...
[info] Resolving org.scala-sbt#io;0.13.15 ...
[info] Resolving org.scala-sbt#control;0.13.15 ...
[info] Resolving org.scala-sbt#launcher-interface;1.0.1 ...
[info] Resolving org.scala-sbt#completion;0.13.15 ...
[info] Resolving org.scala-sbt#collections;0.13.15 ...
[info] Resolving jline#jline;2.14.3 ...
[info] Resolving org.scala-sbt#api;0.13.15 ...
[info] Resolving org.scala-sbt#classfile;0.13.15 ...
[info] Resolving org.scala-sbt#logging;0.13.15 ...
[info] Resolving org.scala-sbt#process;0.13.15 ...
[info] Resolving org.scala-sbt#compiler-integration;0.13.15 ...
[info] Resolving org.scala-sbt#incremental-compiler;0.13.15 ...
[info] Resolving org.scala-sbt#relation;0.13.15 ...
[info] Resolving org.scala-sbt#compile;0.13.15 ...
[info] Resolving org.scala-sbt#persist;0.13.15 ...
[info] Resolving org.scala-tools.sbinary#sbinary_2.10;0.4.2 ...
[info] Resolving org.scala-sbt#compiler-ivy-integration;0.13.15 ...
[info] Resolving org.scala-sbt#ivy;0.13.15 ...
[info] Resolving org.scala-sbt#cross;0.13.15 ...
[info] Resolving org.scala-sbt.ivy#ivy;2.3.0-sbt-48dd0744422128446aee9ac31aa356ee203cc9f4 ...
[info] Resolving com.jcraft#jsch;0.1.50 ...
[info] Resolving org.scala-sbt#serialization_2.10;0.1.2 ...
[info] Resolving org.scala-lang.modules#scala-pickling_2.10;0.10.1 ...
[info] Resolving org.scalamacros#quasiquotes_2.10;2.0.1 ...
[info] Resolving org.json4s#json4s-core_2.10;3.2.10 ...
[info] Resolving org.json4s#json4s-ast_2.10;3.2.10 ...
[info] Resolving com.thoughtworks.paranamer#paranamer;2.6 ...
[info] Resolving org.spire-math#jawn-parser_2.10;0.6.0 ...
[info] Resolving org.spire-math#json4s-support_2.10;0.6.0 ...
[info] Resolving org.scala-sbt#run;0.13.15 ...
[info] Resolving org.scala-sbt#task-system;0.13.15 ...
[info] Resolving org.scala-sbt#tasks;0.13.15 ...
[info] Resolving org.scala-sbt#tracking;0.13.15 ...
[info] Resolving org.scala-sbt#cache;0.13.15 ...
[info] Resolving org.scala-sbt#testing;0.13.15 ...
[info] Resolving org.scala-sbt#test-agent;0.13.15 ...
[info] Resolving org.scala-sbt#test-interface;1.0 ...
[info] Resolving org.scala-sbt#main-settings;0.13.15 ...
[info] Resolving org.scala-sbt#apply-macro;0.13.15 ...
[info] Resolving org.scala-sbt#command;0.13.15 ...
[info] Resolving org.scala-sbt#template-resolver;0.1 ...
[info] Resolving org.scala-sbt#logic;0.13.15 ...
[info] Resolving org.scala-sbt#compiler-interface;0.13.15 ...
[info] Resolving org.scala-lang#jline;2.10.6 ...
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] Done updating.
/..../play-java-rest-api-example/build.sbt:8: error: type mismatch;
found   : Seq[sbt.ModuleID]
required: Set[sbt.ModuleID]
dependencyOverrides := Seq(
^
[error] Type error in expression
Invalid response.
```

**Comment by wsargent** [comment] 2017-11-07 18:29
You most probably use a different sbt version in Intellij IDEA vs the command line.  Try using an EAP verson of IntelliJ IDEA with new Scala plugin.

Closing this, because this is not a bug in the project itself.

**Closed as completed by wsargent** 2017-11-07 18:29 UTC
